In [1]:
import pandas as pd

In [2]:
#2025-10-3 reformatting - below removes dod from wrong lines

import pandas as pd

df = pd.read_csv("euthanasia_log.csv", dtype=str)

def parse_date(x):
    # Try multiple formats
    for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%m/%d/%y"):  
        try:
            return pd.to_datetime(x, format=fmt).strftime("%Y-%m-%d")
        except (ValueError, TypeError):
            continue
    # If none match, return original string so it isn't lost
    return x  

df["DOD"] = df["DOD"].apply(parse_date)

In [3]:
df["DOD"]

0      2025-05-08
1      2025-04-30
2      2025-04-30
3      2025-04-30
4      2025-04-30
          ...
355    2026-03-03
356    2026-03-23
357    2026-03-23
358    2026-03-23
359    2026-03-23
Name: DOD, Length: 360, dtype: object

In [4]:
df

,Animal_ID,Tank,Rack,DOD,DOB,Purpose,Experimenter,Cohort,Environmental_Condition,Lineage,...,Species,Protocol_Number,Experimental_History,RFID,Date_of_Terra,Date_of_Reaqua,Diet,Weight_g,Sex,Complications
0,SAL_673,B1,Rack 5,2025-05-08,12/10/24 0:00,NaN,NaN,NaN,Aquatic,NaN,...,Pleurodeles waltl,AABF2564,NaN,NaN,NaN,NaN,NaN,0.0,Unknown,Found Dead
1,SAL_089,C4,Rack 2,2025-04-30,2/23/22 0:00,Brain atlas,"NJC, TS",NaN,Aquatic,NaN,...,Pleurodeles waltl,AABL1550,LX viral injections,NaN,NaN,NaN,NaN,0.0,Unknown,NaN
2,SAL_090,C4,Rack 2,2025-04-30,2/23/22 0:00,Brain atlas,"NJC, TS",NaN,Aquatic,NaN,...,Pleurodeles waltl,AABL1550,LX viral injections,NaN,NaN,NaN,NaN,0.0,Unknown,NaN
3,SAL_091,C4,Rack 2,2025-04-30,2/23/22 0:00,Brain atlas,"NJC, TS",NaN,Aquatic,NaN,...,Pleurodeles waltl,AABL1550,LX viral injections,NaN,NaN,NaN,NaN,0.0,Unknown,NaN
4,SAL_092,C4,Rack 2,2025-04-30,2/23/22 0:00,Brain atlas,"NJC, TS",NaN,Aquatic,NaN,...,Pleurodeles waltl,AABL1550,LX viral injections,NaN,NaN,NaN,NaN,0.0,Unknown,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,SAL_786,B3,Rack 8,2026-03-03,1/3/25 0:00,AAV CellREADR,PA,NaN,Aquatic,NaN,...,Pleurodeles waltl,AABF2564,NaN,NaN,NaN,NaN,NaN,3.8,Female,NaN
356,SAL_174,B2,Rack 2,2026-03-23,1/14/23 0:00,Sick. Euthanised following vet's suggestion,"NJC, JW",NaN,Aquatic,NaN,...,Pleurodeles waltl,AABL1550,Craniotomy Leucistic; Viral PHPeB CAG G8s,NaN,NaN,NaN,NaN,6.2,Male,Euthanized for Illness
357,SAL_129,C1,Rack 2,2026-03-23,3/1/23 0:00,Sick. Euthanised following vet's suggestion.,"NJC, JW",NaN,Aquatic,NaN,...,Pleurodeles waltl,AABL1550,ECJ - Viral CAG G8s,NaN,NaN,NaN,NaN,3.1,Male,Euthanized for Illness
358,SAL_192,C5,Rack 4,2026-03-23,1/14/23 0:00,Sick. Euthanised following vet's suggestion.,"NJC, JW",Viral,Aquatic,NaN,...,Pleurodeles waltl,AABL1550,Viral PHPeB CAG G8s LX,NaN,NaN,NaN,NaN,5.5,Female,Euthanized for Illness
359,SAL_193,C5,Rack 4,2026-03-23,1/14/23 0:00,Sick. Euthanised following vet's suggestion.,"NJC, JW",Viral,Aquatic,NaN,...,Pleurodeles waltl,AABL1550,Viral PHPeB CAG G8s LX,NaN,NaN,NaN,NaN,4.9,Male,Euthanized for Illness

In [ ]:
#old code

In [2]:
df = pd.read_csv("euthanasia_log.csv", dtype=str)

In [3]:
# Parse, handling 2-digit years:
df["DOD_parsed"] = pd.to_datetime(df["DOD"], format="%m/%d/%y", errors="coerce")

In [4]:
# Add missing century for ambiguous 2-digit years:
mask_missing = df["DOD_parsed"].isna()
df.loc[mask_missing, "DOD_parsed"] = pd.to_datetime(
    df.loc[mask_missing, "DOD"], format="%m/%d/%Y", errors="coerce"
)

In [5]:
# Reformat to the desired string format:
df["DOD"] = df["DOD_parsed"].dt.strftime("%m/%d/%Y")

In [6]:
# Drop the helper column and overwrite:
df = df.drop(columns="DOD_parsed")

In [7]:
df.to_csv("euthanasia_log.csv", index=False)

In [7]:
df["DOD"]

0      2025-05-08
1      2025-04-30
2      2025-04-30
3      2025-04-30
4      2025-04-30
          ...
186    2025-09-30
187    2025-10-01
188    2025-09-30
189    2025-09-12
190    2025-09-16
Name: DOD, Length: 191, dtype: object

In [11]:
df

,Animal_ID,Tank,Rack,DOD,DOB,Purpose,Experimenter,Cohort,Environmental_Condition,Lineage,...,Species,Protocol_Number,Experimental_History,RFID,Date_of_Terra,Date_of_Reaqua,Diet,Weight_g,Sex,Complications
0,SAL_673,B1,Rack 5,2025-05-08,12/10/24 0:00,NaN,NaN,NaN,Aquatic,NaN,...,Pleurodeles waltl,AABF2564,NaN,NaN,NaN,NaN,NaN,0.0,Unknown,Found Dead
1,SAL_089,C4,Rack 2,2025-04-30,2/23/22 0:00,Brain atlas,"NJC, TS",NaN,Aquatic,NaN,...,Pleurodeles waltl,AABL1550,LX viral injections,NaN,NaN,NaN,NaN,0.0,Unknown,NaN
2,SAL_090,C4,Rack 2,2025-04-30,2/23/22 0:00,Brain atlas,"NJC, TS",NaN,Aquatic,NaN,...,Pleurodeles waltl,AABL1550,LX viral injections,NaN,NaN,NaN,NaN,0.0,Unknown,NaN
3,SAL_091,C4,Rack 2,2025-04-30,2/23/22 0:00,Brain atlas,"NJC, TS",NaN,Aquatic,NaN,...,Pleurodeles waltl,AABL1550,LX viral injections,NaN,NaN,NaN,NaN,0.0,Unknown,NaN
4,SAL_092,C4,Rack 2,2025-04-30,2/23/22 0:00,Brain atlas,"NJC, TS",NaN,Aquatic,NaN,...,Pleurodeles waltl,AABL1550,LX viral injections,NaN,NaN,NaN,NaN,0.0,Unknown,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,SAL_291,A4,Rack 11,2025-09-30,12/9/23 0:00,NaN,NaN,Terra O,Terrestrial,F1,...,Pleurodeles waltl,AABL1550,NaN,NaN,7/15/24 0:00,NaN,Gummy Schedule,0.0,Unknown,NaN
187,SAL_455,D3,Rack 8,2025-10-01,11/24/23 0:00,"RNA Extraction - Bulk-seq OE, cDNA Brain (give...",JW,NaN,Aquatic,NaN,...,Pleurodeles waltl,AABL1550,NaN,NaN,NaN,NaN,Gummy Schedule,8.1,Female,NaN
188,SAL_006,C4,Rack 12,2025-09-30,1/21/20,Sickly - noted by Josh,MK,Reptile Rapture - Yellow,Aquatic,NaN,...,Pleurodeles waltl,AABF2564,NaN,NaN,NaN,NaN,NaN,15.0,Male,NaN
189,SAL_512,A1,Rack 1,2025-09-12,7/1/22 0:00,"Brain expansion trial PA, JW OE EP","JW, PA",NaN,Aquatic,Sweden,...,Pleurodeles waltl,AABF2564,NaN,NaN,NaN,NaN,NaN,0.0,Unknown,NaN
190,SAL_131,C5,Rack 2,2025-09-16,3/29/22 0:00,NaN,NaN,F1,Aquatic,NaN,...,Pleurodeles waltl,AABF2564,genotyped +,NaN,NaN,NaN,NaN,0.0,Unknown,Found Dead

,Animal_ID,Tank,Rack,DOD,DOB,Purpose,Experimenter,Cohort,Environmental_Condition,Lineage,...,Protocol_Number,Experimental_History,RFID,Date_of_Terra,Date_of_Reaqua,Diet,Weight_g,Sex,Complications,DOD_clean
0,SAL_673,B1,Rack 5,2025-05-08,12/10/24 0:00,NaN,NaN,NaN,Aquatic,NaN,...,AABF2564,NaN,NaN,NaN,NaN,NaN,0.0,Unknown,Found Dead,2025-05-08
1,SAL_089,C4,Rack 2,2025-04-30,2/23/22 0:00,Brain atlas,"NJC, TS",NaN,Aquatic,NaN,...,AABL1550,LX viral injections,NaN,NaN,NaN,NaN,0.0,Unknown,NaN,2025-04-30
2,SAL_090,C4,Rack 2,2025-04-30,2/23/22 0:00,Brain atlas,"NJC, TS",NaN,Aquatic,NaN,...,AABL1550,LX viral injections,NaN,NaN,NaN,NaN,0.0,Unknown,NaN,2025-04-30
3,SAL_091,C4,Rack 2,2025-04-30,2/23/22 0:00,Brain atlas,"NJC, TS",NaN,Aquatic,NaN,...,AABL1550,LX viral injections,NaN,NaN,NaN,NaN,0.0,Unknown,NaN,2025-04-30
4,SAL_092,C4,Rack 2,2025-04-30,2/23/22 0:00,Brain atlas,"NJC, TS",NaN,Aquatic,NaN,...,AABL1550,LX viral injections,NaN,NaN,NaN,NaN,0.0,Unknown,NaN,2025-04-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,SAL_291,A4,Rack 11,09/30/2025,12/9/23 0:00,NaN,NaN,Terra O,Terrestrial,F1,...,AABL1550,NaN,NaN,7/15/24 0:00,NaN,Gummy Schedule,0.0,Unknown,NaN,2025-09-30
187,SAL_455,D3,Rack 8,10/01/2025,11/24/23 0:00,"RNA Extraction - Bulk-seq OE, cDNA Brain (give...",JW,NaN,Aquatic,NaN,...,AABL1550,NaN,NaN,NaN,NaN,Gummy Schedule,8.1,Female,NaN,2025-10-01
188,SAL_006,C4,Rack 12,09/30/2025,1/21/20,Sickly - noted by Josh,MK,Reptile Rapture - Yellow,Aquatic,NaN,...,AABF2564,NaN,NaN,NaN,NaN,NaN,15.0,Male,NaN,2025-09-30
189,SAL_512,A1,Rack 1,09/12/2025,7/1/22 0:00,"Brain expansion trial PA, JW OE EP","JW, PA",NaN,Aquatic,Sweden,...,AABF2564,NaN,NaN,NaN,NaN,NaN,0.0,Unknown,NaN,2025-09-12
190,SAL_131,C5,Rack 2,09/16/2025,3/29/22 0:00,NaN,NaN,F1,Aquatic,NaN,...,AABF2564,genotyped +,NaN,NaN,NaN,NaN,0.0,Unknown,Found Dead,2025-09-16